import { BaseResultCard } from './common';

export type InvestorResult = BaseResultCard & {
  card: InvestorCard;
};

export type InvestorCard = {
  slug: string;
  name: string | null;
  description: string | null;
  logo: string | null;
  contact: string | null;
  zone: string | null;
  ticket_min_k_euro: number | null;
  ticket_max_k_euro: number | null;
  sectors: string[] | null;
  targeted_company_size_min_ca: string | null;
  targeted_company_size_max_ca: string | null;
  investment_policy: string | null;
  investments_on_ecological_transition: string | null;
  main_investments: string[] | null;
  source_url: string | null;
  data_source: { transformed_pexe_api: TransformedPexeApi | null };
};

type TransformedPexeApi = {
  ID: number | null;
  Date_inscrit: string | null;
  ORI_ID: number | null;
  Societe: string | null;
  TypeEntreprise: string | null;
  Site_Web: string | null;
  ENT_SIRET: string | null;
  ENT_EFFECIF: string | null;
  ENT_CA: string | null;
  ADRESSE_1: string | null;
  ADRESSE_2: string | null;
  ADRESSE_3: string | null;
  ENT_ANNEE_CREA: string | null;
  ENT_APE: string | null;
  TELEPHONE_FIXE: string | null;
  TELEPHONE_MOBILE: string | null;
  Nom: string | null;
  Prenom: string | null;
  Fonction: string | null;
  Service: string | null;
  Email: string | null;
  NOM_USR2: string | null;
  PRENOM_USR2: string | null;
  Fonction_USR2: string | null;
  Service_USR2: string;
  Email_USR2: string | null;
  TELEPHONE_FIXE_USR2: string | null;
  TELEPHONE_MOBILE_USR2: string | null;
  NOM_USR3: string;
  PRENOM_USR3: string;
  Fonction_USR3: string;
  Email_USR3: string;
  TELEPHONE_FIXE_USR3: string;
  TELEPHONE_MOBILE_USR3: string;
  NOM_USR4: string;
  PRENOM_USR4: string;
  Fonction_USR4: string;
  Email_USR4: string;
  TELEPHONE_FIXE_USR4: string;
  TELEPHONE_MOBILE_USR4: string;
  Ville: string | null;
  CP: string | null;
  Groupe: string;
  PAYS: string | null;
  Origine: string | null;
  Vous_êtes: string | null;
  Nom_du_fonds: string | null;
  Taille_du_fonds: string | null;
  Année_de_création: string | null;
  Durée_de_vie_du_fonds: string | null;
  Logo: string | null;
  Type_de_financement: string | null;
  Présentation_synthétique_du_fonds: string | null;
  "Secteurs_d'intervention": string | null;
  Zone_géographique_ciblée: string | null;
  "Présentation_de_la_politique_d'investissement": string | null;
  Taille_des_entreprises_ciblées_en_CA_min: string | null;
  Taille_des_entreprises_ciblées_en_CA_max: string | null;
  'Ticket_min_en_K€': number | null;
  'Ticket_max_en_K€': number | null;
  'Nombre_de_prises_de_participations_estimé_pour_l’année': string | null;
  Nombre_total_de_participations_sur_les_sujets_transition_écologique_et_énergétique_depuis_la_création:
    | string
    | null;
  'Investissement_emblématique_n°1': string | null;
  'Mots_clés_investissement_n°1': string | null;
  'Investissement_emblématique_n°2': string | null;
  'Mots_clés_investissement_n°2': string | null;
  'Investissement_emblématique_n°3': string | null;
  'Mots_clés_investissement_n°3': string | null;
  Label: string | null;
  Rencontre_finances_2022: string | null;
  Newsletter: string | null;
  ENT_EFFECTIF: string;
  CA: string;
};
